# Generated by Django 3.2.7 on 2021-09-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaPrimaria',
            fields=[
                ('id_primaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_e', models.CharField(max_length=50)),
                ('clave_ct', models.CharField(max_length=12)),
                ('calle_e', models.CharField(max_length=50)),
                ('colonia_e', models.CharField(max_length=50)),
                ('municipio_e', models.CharField(max_length=50)),
                ('estado_e', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_t', models.CharField(max_length=50)),
                ('ap_paterno_t', models.CharField(max_length=50)),
                ('ap_materno_t', models.CharField(max_length=50)),
                ('calle_t', models.CharField(max_length=50)),
                ('numero_casa_t', models.CharField(max_length=50)),
                ('colonia_t', models.CharField(max_length=50)),
                ('ciudad_t', models.CharField(max_length=50)),
                ('estado_t', models.CharField(max_length=50)),
                ('telefono_t', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('escolaridad', models.CharField(max_length=50)),
                ('parentesco', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Tia', 'Tia'), ('Tio', 'Tio'), ('Abuela', 'Abuela'), ('Abuelo', 'Abuelo'), ('Hermana', 'Hermana'), ('Hermano', 'Hermano')], max_length=10)),
                ('edad_t', models.CharField(max_length=3)),
                ('fecha_nacimiento_t', models.DateField()),
                ('email_t', models.CharField(max_length=50)),
                ('nacionalidad_t', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('num_casa_a', models.CharField(max_length=10)),
                ('colonia_a', models.CharField(max_length=50)),
                ('ciudad_a', models.CharField(max_length=50)),
                ('estado_a', models.CharField(max_length=50)),
                ('pais_a', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('telefono_alumno', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=6)),
                ('curp_a', models.CharField(max_length=18)),
                ('email_alumno', models.CharField(max_length=80)),
                ('promedio_quinto_grado', models.FloatField(max_length=3)),
                ('id_primaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.escuelaprimaria')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinscripcion.tutor')),
            ],
        ),
    ]
